name       : expat
version    : 2.5.0
release    : 26
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.xz : ef2420f0232c087801abf705e89ae65f6257df6b7931d37846a193ef2e8cdcbe
homepage   : https://libexpat.github.io/
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
check      : |
    %make check
