name       : expat
version    : 2.2.7
release    : 16
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_2_7/expat-2.2.7.tar.xz : 30e3f40acf9a8fdbd5c379bdcc8d1178a1d9af306de29fc8ece922bc4c57bef8
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
