name       : expat
version    : 2.2.1
release    : 10
source     :
    - https://ncu.dl.sourceforge.net/project/expat/expat/2.2.1/expat-2.2.1.tar.bz2 : 1868cadae4c82a018e361e2b2091de103cd820aaacb0d6cfa49bd2cd83978885
license    :
    - GPL-3.0
component  : system.base
summary    : XML Parsing Library
emul32     : yes
devel      : true
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
