name       : expat
version    : 2.2.9
release    : 17
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.xz : 1ea6965b15c2106b6bbe883397271c80dfa0331cdf821b2c319591b55eadc0a4
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
