name       : expat
version    : 2.2.3
release    : 11
source     :
    - https://netix.dl.sourceforge.net/project/expat/expat/2.2.3/expat-2.2.3.tar.bz2 : b31890fb02f85c002a67491923f89bda5028a880fd6c374f707193ad81aace5f
license    : GPL-3.0
component  : system.base
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
