name       : expat
version    : 2.4.5
release    : 23
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_4_5/expat-2.4.5.tar.gz : 9e88fb86a0220ab5c1fcf42c187857c2151534b7a4d88741c9405df5be449a3d
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
check      : |
    %make check
