name       : expat
version    : 2.4.9
release    : 25
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_4_9/expat-2.4.9.tar.xz : 6e8c0728fe5c7cd3f93a6acce43046c5e4736c7b4b68e032e9350daa0efc0354
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
check      : |
    %make check
