name        : expat
version     : 2.1.1
release     : 7
source     :
    - https://sourceforge.net/projects/expat/files/expat/2.1.1/expat-2.1.1.tar.bz2 : aff584e5a2f759dcfc6d48671e9529f6afe1e30b0cd6a4cec200cbe3f793de67
license     :
    - GPL-3.0
summary     : XML Parsing Library
description : |
    The Expat package contains a stream oriented C library for parsing XML.
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
devel      : true
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
