name       : expat
version    : 2.2.5
release    : 13
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2 : d9dc32efba7e74f788fcc4f212a43216fc37cf5f23f4c2339664d473353aedf6
license    : GPL-3.0
component  : system.base
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
