name       : expat
version    : 2.2.6
release    : 14
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2 : 17b43c2716d521369f82fc2dc70f359860e90fa440bea65b3b85f0b246ea81f2
license    : MIT
component  : system.base
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
