name       : expat
version    : 2.2.0
release    : 9
source     :
    - https://sourceforge.net/projects/expat/files/expat/2.2.0/expat-2.2.0.tar.bz2 : d9e50ff2d19b3538bd2127902a89987474e1a4db8e43a66a4d1a712ab9a504ff
license    :
    - GPL-3.0
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
emul32     : yes
devel      : true
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
