name       : expat
version    : 2.4.7
release    : 24
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_4_7/expat-2.4.7.tar.gz : 72644d5f0f313e2a5cf81275b09b9770c866dd87a2b62ab19981657ac0d4af5f
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
check      : |
    %make check
