name       : expat
version    : 2.2.4
release    : 12
source     :
    - https://netix.dl.sourceforge.net/project/expat/expat/2.2.4/expat-2.2.4.tar.bz2 : 03ad85db965f8ab2d27328abcf0bc5571af6ec0a414874b2066ee3fdd372019e
license    : GPL-3.0
component  : system.base
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
