name       : expat
version    : 2.4.3
release    : 21
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_4_3/expat-2.4.3.tar.gz : 70612344a2723cc7cae06644f5d3d58e054d5be3e9d6695d3505c8d3e9a4be4b
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
check      : |
    %make check
