name       : expat
version    : 2.4.1
release    : 20
source     :
    - https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.xz : cf032d0dba9b928636548e32b327a2d66b1aab63c4f4a13dd132c2d1d2f2fb6a
license    : MIT
component  :
    - system.base
    - devel : system.devel
emul32     : yes
summary    : XML Parsing Library
description: |
    The Expat package contains a stream oriented C library for parsing XML.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
check      : |
    %make check
